// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krsmsjfyopncjoaeqpkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtyc21zamZ5b3BuY2pvYWVxcGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA4MTkxMjYsImV4cCI6MjEwNjM5NTEyNn0.xQSeRjaCJHQD8469v4dzlHyJLOlmg0eYhHbqLyGP9No";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});