// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buzxmlennffrzgmggbig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1enhtbGVubmZmcnpnbWdnYmlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjQ2MjMsImV4cCI6MjA2OTQwMDYyM30.2BjYYgGD2AdOZAXwNPJ20Po1ofoLLrKlB-St08PCTuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});